version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hexvault_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_passwd
      POSTGRES_DB: hexvault
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
